### ISSUE TITLE
Can't parse Geth node's ENR

### ISSUE THREAD

**Issue by frostRed** [rust-ethereum/enr#3]
I find it can't parse Geth node's ENR like this:
``` 
enr:-Je4QIdx4eWpaemy4ECbJU2ZsXvzX3XsiF10QOjm-87XBkoaJdEq3qjijY7fMkhP1SZRUeqHodSczUCuj01eWWzQ2xc7g2V0aMfGhOAp6ZGAgmlkgnY0gmlwhLecb4iJc2VjcDI1NmsxoQPnve6T4T8AWndeYCCi-zJncpl_W_SR8Wky_rUI8MxR24N0Y3CCdmCDdWRwgnZg
```
I get Error `Custom("List decode fail")`
But It can be parsed well by Geth.

**Comment by AgeManning** [comment]
Hey!

Sorry, I missed this issue. 

The ENR given here looks like it has not been RLP encoded correctly. Can you give me the contents of the ENR and/or how it was created?

I've not seen other issues with geth so far, so this is strange.

**Comment by Enigmatic331** [comment]
I guess the above ENR is similar to the ENR as obtained from the discv4-dns-lists repo (e.g. https://github.com/ethereum/discv4-dns-lists/blob/master/all.mainnet.ethdisco.net/nodes.json) - Which would likewise be a decode fail (testing through enr-cli).

**Comment by AgeManning** [comment]
Awesome thanks, I'll look into this.

**Comment by AgeManning** [comment]
So this appears to be that geth is using extra lists in some of their ENR keys. This should be a straight forward fix. I'll write out another issue and we should have this corrected very soon. 

I'll close this issue once it's merged
